import { Subject } from './contentLoader';

export const SUBJECTS: Subject[] = [
  {
    id: 'algebra',
    title: 'Algebra',
    description: 'From equations and inequalities to functions, polynomials, exponentials, systems, and sequences—structured for precalculus and beyond.',
    path: '/algebra/'
  },
  {
    id: 'calculus1',
    title: 'Calculus 1',
    description: 'Single-variable calculus from limits to integration. Six sections cover functions, derivatives, differentiation rules, applications, the definite integral, and antiderivatives.',
    path: '/calculus1/'
  },
  {
    id: 'calculus2',
    title: 'Calculus 2',
    description: 'Integration techniques, improper integrals, sequences, series, and convergence tests.',
    path: '/calculus2/'
  },
  {
    id: 'calculus3',
    title: 'Calculus 3',
    description: 'Vectors, 3D functions, partial derivatives, multiple integrals, and vector calculus.',
    path: '/calculus3/'
  },
  {
    id: 'linearalg',
    title: 'Linear Algebra',
    description: 'Matrices, vector spaces, linear transformations, determinants, and eigenvectors.',
    path: '/linearalg/'
  },
  {
    id: 'diffeq',
    title: 'Differential Equations',
    description: 'First and second order ODEs, Laplace transforms, systems of ODEs, and series solutions.',
    path: '/diffeq/'
  }
];

export const SUBJECT_FILES: Record<string, string[]> = {
  algebra: [
    'Chapter 1.1 Review of Algebra.md',
    'Chapter 1.2 Equations and Inequalities.md',
    'Chapter 2.1 Functions.md',
    'Chapter 2.2 Transformations.md'
  ],
  calculus1: [
    'Chapter 1.1 Functions and Change.md',
    'Chapter 1.2 Exponential Functions.md',
    'Chapter 1.3 New Functions from Old.md',
    'Chapter 1.4 Logarithmic Functions.md',
    'Chapter 1.5 Trigonometric Function.md',
    'Chapter 1.6 Powers, Polynomials, and Rational Functions.md',
    'Chapter 1.7 Introduction to Limits and Continuity.md',
    'Chapter 1.8 Extending the Idea of a Limit.md',
    'Chapter 1.9 Further Limit Calculations Using Algebra.md',
    'Chapter 2.1 How Do We Measure Speed.md',
    'Chapter 2.2 The Derivative at a Point.md',
    'Chapter 2.3 The Derivative Function.md',
    'Chapter 2.4 Interpretations of the Derivative.md',
    'Chapter 2.5 The Second Derivative.md',
    'Chapter 3.1 Powers and Polynomials.md',
    'Chapter 3.2 The Exponential Functions.md',
    'Chapter 3.3 The Product and Quotient Rules.md',
    'Chapter 3.4 The Chain Rule.md',
    'Chapter 3.5 Trigonometric Functions.md',
    'Chapter 3.6 The Chain Rule and Inverse Functions.md',
    'Chapter 3.7 Implicit Functions.md',
    'Chapter 3.8 Hyperbolic Functions.md',
    'Chapter 3.9 Linear Approximation and the Derivative.md',
    'Chapter 3.10 Theorems About Differentiable Functions.md',
    'Chapter 4.1 Using the First and Second Derivatives.md',
    'Chapter 4.2 Optimization.md',
    'Chapter 4.3 Optimization and Modeling.md',
    'Chapter 4.4 Families of Functions and Modeling.md',
    'Chapter 4.5 Applications to Marginality.md',
    'Chapter 4.6 Rate and Related Rates.md',
    'Chapter 4.7 L\'hopital\'s Rule.md',
    'Chapter 4.8 Parametric Equations.md',
    'Chapter 5.1 How do we Measure Distance Traveled.md',
    'Chapter 5.2 The Definite Integral.md',
    'Chapter 5.3 The Fundamental Theorem and Interpretations.md',
    'Chapter 5.4 Theorems About Definite Integrals.md',
    'Chapter 6.1 Antiderivatives Graphically and Numerically.md',
    'Chapter 6.2 Constructing Antiderivatives Analytically.md',
    'Chapter 6.3 Differential Equations and Motion.md',
    'Chapter 6.4 Second Fundamental Theorem of Calculus.md'
  ],
  calculus2: [
    'Chapter 7.1 Integration by Substitution.md',
    'Chapter 7.2 Integration by Parts.md',
    'Chapter 7.3 Tables of Integrals.md',
    'Chapter 7.4 Algebraic Identities and Trigonometric Substitutions.md',
    'Chapter 7.5 Numerical Methods for Definite Integrals.md',
    'Chapter 7.6 Improper Integrals.md',
    'Chapter 7.7 Comparison of Improper Integrals.md',
    'Chapter 9.1 Sequences.md',
    'Chapter 9.2 Geometric Series.md',
    'Chapter 9.3 Convergence of Series.md',
    'Chapter 9.4 Tests for Convergence.md',
    'Chapter 9.5 Power Series and Interval of Convergence.md',
    'Chapter 10.1 Taylor Polynomials.md',
    'Chapter 10.2 Taylor Series.md',
    'Chapter 10.3 Finding and Using Taylor Series.md',
    'Chapter 12.1 Functions of Two Variables.md',
    'Chapter 12.2 Graphs and Surfaces.md',
    'Chapter 12.3 Contour Diagrams.md',
    'Chapter 12.4 Linear Functions.md'
  ],
  calculus3: [
    'Lecture 11.1 An Introduction to Vectors.md',
    'Lecture 11.2 Vectors in 3D Coordinate System.md',
    'Lecture 11.3 Using the Dot Product.md',
    'Lecture 11.4 The Cross Product.md',
    'Lecture 11.5 Lines and Planes in 3D.md',
    'Lecture 11.6 Cylinders and Surfaces in 3D.md',
    'Lecture 11.7 Using Cylindrical and Spherical Coordinates.md',
    'Lecture 12.2 Derivatives and Integrals of Vector Functions.md',
    'Lecture 12.3 Arc Length and Parameterization.md',
    'Lecture 12.4 Frenet-Serret Frames, Curvature, Torsion, and Encapsulation.md',
    'Lecture 13.1 Introduction to Multivariable Functions.md',
    'Lecture 13.2 Limits and Continuity of Multivariable Functions.md',
    'Lecture 13.3 Partial Derivatives.md',
    'Lecture 13.4 Finding Differentials of Multivariable Functions.md',
    'Lecture 13.5 The Chain Rule for Multivariable Functions.md',
    'Lecture 13.6 Finding Directional Derivatives and Gradients.md',
    'Lecture 13.7 Finding Tangent Planes and Normal Lines to Surfaces.md',
    'Lecture 13.8 Finding Extrema of Functions of 2 Variables.md',
    'Lecture 13.9 Constrained Optimization with Lagrange Multipliers.md',
    'Lecture 14.1 Introduction to Double Integrals.md',
    'Lecture 14.2 Solving Iterated Integrals.md',
    'Lecture 14.3 Double Integrals over Polar Regions.md',
    'Lecture 14.6 Solving Triple Integrals.md',
    'Lecture 14.7 Triple Integrals Over Regions with Cylindrical or Spherical Coordinates.md',
    'Lecture 14.8 How to Change Variables in Multiple Integrals.md',
    'Lecture 15.1 Introduction to Vector Fields.md',
    'Lecture 15.2 How to Find Divergence and Curl of Vector Fields.md',
    'Lecture 15.3 How to Compute Line Integrals.md',
    'Lecture 15.4 Line Integrals on Conservative Vector Fields.md',
    'Lecture 15.5 Green\'s Theorem.md',
    'Lecture 15.6 Surface and Flux Integrals, Parametric Surfaces, Stroke\'s Theorem.md'
  ],
  linearalg: [
    '1.1 Systems of Linear Equations.md',
    '1.2 Row Reduction and Echelon Forms.md',
    '1.3 Vector Equations.md',
    '1.4 The Matrix Equation.md',
    '1.5 Solution Sets of Linear Systems.md',
    '1.6 Applications of Linear Systems.md',
    '1.7 Linear Independence.md',
    '1.8 Introduction to Linear Transformations.md',
    '1.9 The Matrix of a Linear Transformation.md',
    '2.1 Matrix Operations.md',
    '2.2 The Inverse of a Matrix.md',
    '2.3 Characterization of Invertible Matrices.md',
    '2.4 Partitioned Matrices.md',
    '3.1 Determinants.md',
    '3.2 Properties of Determinants.md',
    '3.3 Cramer\'s Rule.md',
    '4.1 Vector Spaces and Subspaces.md',
    '4.2 Null Spaces, Column Spaces, and Linear Transformations.md',
    '4.3 Linearly Independent Sets, Bases.md',
    '4.4 Coordinate Systems.md',
    '4.5 The Dimension of a Vector Space.md',
    '4.6 Rank.md',
    '5.1 Eigenvectors and Eigenvalues.md',
    '5.2 The Characteristic Equation.md',
    '5.3 Diagonalization.md',
    '6.1 Inner Product, Length, and Orthogonality.md',
    '6.2 Orthogonal Sets.md',
    '6.3 Orthogonal Projections.md',
    '6.4 The Gram-Schmidt Process.md',
    '7.1 Diagonalization of Symmetric Matrices.md',
    '7.2 Quadratic Forms.md'
  ],
  diffeq: [
    '1.3 Classification of Differential Equations.md',
    '2.1 Linear Differential Equations.md',
    '2.2 Separable Differential Equations.md',
    '2.3 Modeling with First Order Differential Equations.md',
    '2.6 Exact Differential Equations.md',
    '2.7 Euler\'s Method.md',
    '3.1 Homogenous Differential Equations with Constant Coefficients.md',
    '3.2 The Wronskian.md',
    '3.3 Complex Roots of the Characteristic Equations.md',
    '3.4 Repeated Roots.md',
    '3.5 Nonhomogeneous Equations, Method of Undetermined Coefficients.md',
    '3.6 Variation of Parameters.md',
    '4.1 Theory of Linear Differential Equations.md',
    '4.2 Higher Order Homogeneous Equations with Constant Coefficients.md',
    '4.3 Method of Undetermined Coefficients 2.md',
    '6.1 The Laplace Transform.md',
    '6.2 Solutions of Initial Value Problems.md',
    '6.3 Step Functions.md',
    '6.4 Differential Equations with Discontinuous Forcing Functions.md',
    '6.5 Impulse Functions.md',
    '6.6 The Convolution Integral.md',
    '7.2 Review of Matrices.md',
    '7.3 Systems of Equations, Eigenvalues, Eigenvectors.md',
    '7.4 Theory of Systems of Linear Differential Equations.md',
    '7.5 Homogenous Linear Systems with Constant Coefficients.md',
    '7.6 Complex-Valued Eigenvalues.md',
    '7.7 Fundamental Matrices.md',
    '7.9 Nonhomogeneous Linear Systems.md'
  ]
};

export const CHAPTER_TITLES: Record<string, Record<string, string>> = {
  calculus1: {
    '1': 'Foundations',
    '2': 'Derivatives', 
    '3': 'Differentiation Rules',
    '4': 'Applications',
    '5': 'Integration Concepts',
    '6': 'Antiderivatives & ODEs'
  },
  calculus2: {
    '7': 'Integration Techniques',
    '9': 'Sequences and Series',
    '10': 'Taylor Series',
    '12': 'Multivariable Functions'
  },
  calculus3: {
    '11': 'Vectors and the Geometry of Space',
    '12': 'Vector Functions',
    '13': 'Partial Derivatives',
    '14': 'Multiple Integrals',
    '15': 'Vector Calculus'
  },
  linearalg: {
    '1': 'Systems of Linear Equations',
    '2': 'Matrix Algebra',
    '3': 'Determinants',
    '4': 'Vector Spaces',
    '5': 'Eigenvalues and Eigenvectors',
    '6': 'Orthogonality',
    '7': 'Symmetric Matrices'
  },
  diffeq: {
    '1': 'First Order Differential Equations',
    '2': 'First Order Equations',
    '3': 'Second Order Linear Equations',
    '4': 'Higher Order Equations',
    '6': 'Laplace Transforms',
    '7': 'Systems of Differential Equations'
  },
  algebra: {
    '1': 'Fundamentals',
    '2': 'Functions and Graphs',
    '3': 'Polynomial Functions'
  }
};
